--- 
title: "Practical Optimization in Operations Research using CPLEX Java API"
author: "Kunlei Lian"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: kunlei/practial-opt-cplex-java
description: "A guided tour of using CPLEX Java API to solve optimization problems."
---

# Preface {- #preface}

Students majoring in industrial engineering (IE) or operations research (OR) might relate to the unpleasant experience of using CPLEX, or other optimization software, for the first time to solve optimization problems on their own.
Equipped with solid background in optimization theories and techniques, which often requires years of proudly hard work, wielding a tool like CPLEX to attack an optimization puzzle should be a trivial task - afterall, if one can single-handedly derive the Simplex tableaux to solve daunting linear programming problems, how hard could it be to simply use a solver that encapsulates its inner workings and provides a convenient function `solve()` to do all the heavy lifing?

It surely is not, but only after one gets over the initial learning curve.
Put it in another way, making a successuful call to the function `solve()` is no more difficult than pushing the *Start* button to start a vehicle, but one has to have a car (obtain a copy of CPLEX), retrieve the key (install CPLEX on the system), open the door (include CPLEX libraries in the program) and locate the button (build the model using CPLEX) before the `Start` button can be actually pushed, and a Ph.D. in mechanical (industrial) engineering does not necessarily help in this adventure.

Academic endeavor aside, industry practitioners from two broad schools may find themselves facing chalenges to employ CPLEX to fulfill their needs.
One encompasses the data scientists with mainly descriptive or predictive analytics background who are occasionally tasked with solving prescriptive analytics problems of small scale and limited complexity.
Usually the underlying mathematical models are straightforward to build, and the difficulty lies in setting up and running CPLEX with minimal efforts.
The other is comprised of experienced OR professionals aiming to solve real-world large-scale optimization problems for which advanced optimization algorithms must be designed and implemented in a correct and timely manner.
Often times the algorithmic framework is similar, only certain problem-specific details need to be hammered out.
In this case, example codes of the algorithm applied to other problems could jumpstart the development work to solve the problem at hand.

Yet, while those who need CPLEX continue to succeed in learning it - the large number of academic papers published every year that use CPLEX as the solver suggest this, there is no lack of frustrations in the learning journey - desperate posts pop up online everyday asking for help to address their CPLEX issues.
On the one hand, there is no dearth of useful information related to CPLEX to help beginners flatten the curve, as can be found in numerous online tutorials, blogs, forums, and so on. 
Most, if not all, questions in learning and using CPLEX have already been asked and answered by its users all over the world, and determined newcomers can evenly get out of the information labyrinth with the help of , usually many, google searches. 
On the other hand, there yet exists a comprehensive treatement of this subject that guides first-time CPLEX users through the initial learning hurdle or provides a starting point on some advanced optimization algorithms for somewhat more experienced users.
This book is an attempt to make a stride in this direction.

This book is divided into the following chapters:

**Chapter 1** introduces the ILOG CPLEX and the various ways to interact with it through programming APIs.

**Chapter 2** details the installation and setup process.

**Chapter 3** presents an overview of the CPLEX Java API.
